import {
  mdiHeart,
  mdiLightningBolt,
  mdiFoodDrumstick,
  mdiSleep,
  mdiSkullCrossbones,
  mdiWater,
  mdiCash,
  mdiAccountGroup,
  mdiEmoticon,
  mdiCat,
  mdiCastle,
  mdiCoffee,
  mdiGoogleDownasaur,
  mdiPalette,
  mdiTeddyBear,
  mdiAtom,
  mdiBacteriaOutline,
  mdiBadminton,
  mdiHeadFlashOutline,
  mdiHeadHeartOutline,
  mdiHeadLightbulbOutline,
  mdiCrown,
  mdiCupcake,
  mdiPigVariantOutline,
  mdiFaceWomanShimmerOutline,
} from "@mdi/js";

const icons = {
  Heart: mdiHeart,
  "Lightning Bolt": mdiLightningBolt,
  "Food Drumstick": mdiFoodDrumstick,
  Sleep: mdiSleep,
  "Skull Crossbones": mdiSkullCrossbones,
  Water: mdiWater,
  Cash: mdiCash,
  "Account Group": mdiAccountGroup,
  Emoticon: mdiEmoticon,
  Cat: mdiCat,
  Castle: mdiCastle,
  Coffee: mdiCoffee,
  "Google Downasaur": mdiGoogleDownasaur,
  Palette: mdiPalette,
  "Teddy Bear": mdiTeddyBear,
  atom: mdiAtom,
  "Bacteria Outline": mdiBacteriaOutline,
  Badminton: mdiBadminton,
  "Head Flash Outline": mdiHeadFlashOutline,
  "Head Heart Outline": mdiHeadHeartOutline,
  "Head Lightbulb Outline": mdiHeadLightbulbOutline,
  Crown: mdiCrown,
  Cupcake: mdiCupcake,
  "Pig Variant Outline": mdiPigVariantOutline,
  "Face Woman Shimmer Outline": mdiFaceWomanShimmerOutline,
};

export default icons;
