const icons = [
  "mdi-heart",
  "mdi-lightning-bolt",
  "mdi-food-drumstick",
  "mdi-sleep",
  "mdi-skull-crossbones",
  "mdi-water",
  "mdi-cash",
  "mdi-account-group",
  "mdi-emoticon",
  "mdi-cat",
  "mdi-castle",
  "mdi-coffee",
  "mdi-google-downasaur",
  "mdi-palette",
  "mdi-teddy-bear",
  "mdi-atom",
  "mdi-bacteria-outline",
  "mdi-badminton",
  "mdi-head-flash-outline",
  "mdi-head-heart-outline",
  "mdi-head-lightbulb-outline",
  "mdi-crown",
  "mdi-cupcake",
  "mdi-pig-variant-outline",
  "mdi-face-woman-shimmer-outline",
];

export default icons;
